### ISSUE TITLE
 PCB registration

### ISSUE THREAD

**Issue by Ixiaohuihuihui** [wenzelian/Image-Registration#5]

**Comment by ZeLianWen** [comment]
Robust Image Registration of Printed Circuit Boards Using Improved SIFT-PSO Algorithm

**Comment by ZeLianWen** [comment]
http://digital-library.theiet.org/content/journals/10.1049/joe.2018.8274

**Comment by Ixiaohuihuihui** [comment]
Thanks for sharing the repository! and I just don't know whether this method suitable for defect detection in PCB, but when I use your method, it performance well in PCB registration.
